name: samba

services:
  samba:
    image: crazymax/samba
    container_name: samba
    network_mode: host
    cap_add:
      - CAP_NET_ADMIN
      - CAP_NET_RAW
    volumes:
      - "./data:/data"
      - "/mnt/mediapool:/mediapool"
    environment:
      - "TZ=America/Anchorage"
      - "SAMBA_LOG_LEVEL=0"
      - "WSDD2_ENABLE=1"
    restart: always
